import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import {
  // ReactElement,
  // JSXElementConstructor,
  ReactNode, useEffect, useState,
  // ReactPortal,
  // PromiseLikeOfReactNode,
} from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: any) {
  const [state, setState] = useState()

  console.log(props);
   const newWord = () => {
    fetch('api/vocapi')
    .then(response=>response.json())
    .then(data=>setState(data))
   }
   
    let randomWord
    // console.log(state.englishList[0].data);
  
  if (state) {
    const array = state.englishList[0].data
    randomWord=array[Math.floor(Math.random() * array.length)].en
    console.log(randomWord);

    
  }

  
  useEffect(() => {
    newWord()
  
   
  }, [])
  
  return (
    <>
      <Head>
        <title>Cours React Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* <Navbar/> */}

        <h1 className={styles.titre}>Mot au hasard </h1>
        {/* <h1 className={styles.titre}>Vocabulaire de base </h1> */}
        {/* <table className={styles.tableau}>
          <tbody>
            {props.array.map((el: { [x: string]: ReactNode; en: string }) => (
              <tr key={el.en}>
                <td>{el.en}</td>
                <td>{el.fr}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <a href="https://google.com">Google</a> */}
        <button className="btn btn-primary" onClick={newWord}>Bouton</button>
        <h2>{randomWord}</h2>
        <Link href={"/blog"}>Blog</Link>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await import("../data/vocabulary.json");
  const array = data.vocabulary;
  // if (array.length===0) {
  //   return{
  //     notFound: true
  //   }

  // }
  if (array.length === 0) {
    return {
      redirect: {
        destination: "/isr",
      },
    };
  }
  return {
    props: {
      array,
    },
  };
}
